[package]
name = "dogity"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
ic-cdk = "0.12"
ic-cdk-macros = "0.8"
candid = "0.9"
serde = { version = "1.0", features = ["derive"] }
dogecoin = "0.30" 